### ISSUE TITLE
Problem with array argv in argument of main function

### ISSUE THREAD

**Issue by KnifeOnlyI** [PhilippRados/wrecc#5]
Hi, good job ! 

I've tested the Wrecc compiler and found an error. I couldn't find in the documentation whether it's a feature that isn't already supported. Forgive me if this is not the case.

```c
#include <stdio.h>

int main(int argc, char *argv[]) {
    printf("Hello, World!\n");
    return 0;
}
```

The compiler generate this error : 

```
error: expected expression, found: ']'
|  --> in main.c:3:31
|
3 int main(int argc, char *argv[]) {
|                               ^
1 error generated.
```

Unfortunately, I don't have the required skills to fix this and propose a pull request.

**Comment by PhilippRados** [comment]
Yes arrays with unspecified size aren't yet supported.

**Comment by KnifeOnlyI** [comment]
Oh excuse me. I close this issue.
